AWSTemplateFormatVersion: '2010-09-09'
Description: Provisions a secure S3 bucket and a CloudFront distribution with Origin Access Identity.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced