apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  labels:
    app: web-frontend
    app.kubernetes.io/name: web-frontend
    app.kubernetes.io/part-of: web-frontend
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: false
  selector:
    app: web-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      appProtocol: http
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      appProtocol: https