apiVersion: v1
kind: Pod
metadata:
  name: secure-nginx-pod
  labels:
    app: secure-nginx
spec:
  containers:
  - name: nginx
    image: nginxinc/nginx-unprivileged:1.25-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - name: http