apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
data:
  nginx.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;