apiVersion: v1
kind: Service
metadata:
  name: web-frontend-lb
  labels:
    app: web-frontend
    app.kubernetes.io/name: web-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: web-application
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: web-frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https