apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule:
    - cron: 0 2 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: myorg/db-backup:2.1
            command: ["db-backup"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  timezone: UTC