AWSTemplateFormatVersion: '2010-09-09'
Description: 'Production-Grade 3-Tier VPC across 3 AZs with Public, Application, and Database subnets.'

Parameters:
  EnvironmentName:
    Type: String
    Description: An environment name that will be prefixed to resource names.
    Default: 'Prod'