apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-crd-manager-clusterrole
  labels:
    app.kubernetes.io/name: my-operator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: iac
rules: