apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-operator-manager-role
  labels:
    app.kubernetes.io/name: my-operator
    app.kubernetes.io/managed-by: expert-iac
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.example.com # FIXME: Replace with your operator's API group
  resources:
  - myresources # FIXME: Replace with the plural name of your custom resource
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.example.com # FIXME: Replace with your operator's API group
  resources:
  - myresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mygroup.example.com # FIXME: Replace