- hosts: all
  become: true
  vars:
    # This variable must be defined and encrypted using ansible-vault
    # Example: ansible-vault encrypt_string 'ssh-ed25519 AAAA...' --name 'vault_deploy_user_ssh_key'
    vault_deploy_user_ssh_key: "CHANGEME_VAULT