AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a CloudWatch Dashboard to monitor the health of a specific Lambda function.

Parameters:
  FunctionName:
    Type: String
    Description: The name of the Lambda function to monitor.
  DashboardName:
    Type: String
    Description: The name for the CloudWatch