apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      runAsUser: 1001
      fsGroup: 1001
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx
      readOnly: true
  volumes:
  - name: nginx-config
    emptyDir: {}
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
    supplementalGroups:
    - 1001