AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Production-Ready 3-Tier VPC across 3 AZs with Public, Application, and Database subnets.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names.
    Type: String
    Default: