AWSTemplateFormatVersion: '2010-09-09'
Description: Provisions an SQS-triggered Lambda function named 'order-processor'.

Resources:
  OrderProcessorQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: order-processor-dlq
      KmsMasterKeyId: alias/aws