AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Production-grade ECS Fargate cluster with two microservices behind an internal
  Network Load Balancer.

Parameters:
  VpcCidr:
    Type: String
    Default: '10.10.0.0/16'