AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Creates a CloudWatch Dashboard to monitor key health metrics for a specific
  Lambda function, including invocations, errors, throttles, and duration.

Parameters:
  LambdaFunctionName:
    Type: String
    Description: The name of the Lambda function