# IaC-Eval Prompt: create an aws_lex_bot for ordering pizzas and include a lambda function
# Generated by: LLM (zero-shot, IaC-Eval benchmark)

provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_role" "lambda_role" {
  name = "pizza_bot_lambda_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

resource "aws_lambda_function" "pizza_order" {
  function_name = "pizza_order_handler"
  role          = aws_iam_role.lambda_role.arn
  handler       = "index.handler"
  runtime       = "python3.9"
  filename      = "lambda.zip"

  environment {
    variables = {
      ENV = "production"
    }
  }
}

resource "aws_lambda_permission" "lex_invoke" {
  statement_id  = "AllowLexInvocation"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.pizza_order.function_name
  principal     = "lex.amazonaws.com"
}

resource "aws_lex_intent" "order_pizza" {
  name = "OrderPizza"

  fulfillment_activity {
    type = "CodeHook"

    code_hook {
      message_version = "1.0"
      uri             = aws_lambda_function.pizza_order.arn
    }
  }

  sample_utterances = [
    "I would like to order a pizza",
    "Order a pizza",
    "Can I get a pizza",
    "I want pizza",
    "Pizza please",
  ]

  slot {
    name     = "PizzaSize"
    priority = 1

    slot_constraint = "Required"
    slot_type       = "AMAZON.AlphaNumeric"

    value_elicitation_prompt {
      max_attempts = 2

      message {
        content      = "What size pizza would you like? Small, medium, or large?"
        content_type = "PlainText"
      }
    }
  }

  slot {
    name     = "PizzaTopping"
    priority = 2

    slot_constraint = "Required"
    slot_type       = "AMAZON.AlphaNumeric"

    value_elicitation_prompt {
      max_attempts = 2

      message {
        content      = "What topping would you like?"
        content_type = "PlainText"
      }
    }
  }
}

resource "aws_lex_bot" "pizza_bot" {
  name             = "PizzaOrderBot"
  child_directed   = false
  process_behavior = "BUILD"

  abort_statement {
    message {
      content      = "Sorry, I am not able to assist at this time."
      content_type = "PlainText"
    }
  }

  clarification_prompt {
    max_attempts = 2

    message {
      content      = "I didn't understand you. Can you please repeat?"
      content_type = "PlainText"
    }
  }

  intent {
    intent_name    = aws_lex_intent.order_pizza.name
    intent_version = "$LATEST"
  }
}
