# IaC-Eval Prompt: Configure a health check with route 53 that uses a cloudwatch metric alarm called "foobar". Set the metric_name to "CPUUtilization", namespace to "AWS/EC2", statistic to "Average", period to "120", and comparison_operator to "GreaterThanOrEqualToThreshold". If the health check doesn't have enough info about the alarm, the status should be "Healthy". All resources should be provisioned in "us-east-1"
# Generated by: LLM (zero-shot, IaC-Eval benchmark)

provider "aws" {
  region = "us-east-1"
}

resource "aws_cloudwatch_metric_alarm" "foobar" {
  alarm_name          = "foobar"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 2
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = 120
  statistic           = "Average"
  threshold           = 80

  alarm_description = "This metric monitors EC2 CPU utilization"
}

resource "aws_route53_health_check" "example" {
  type                            = "CLOUDWATCH_METRIC"
  cloudwatch_alarm_name           = aws_cloudwatch_metric_alarm.foobar.alarm_name
  cloudwatch_alarm_region         = "us-east-1"
  insufficient_data_health_status = "Healthy"
}
