- hosts: all
  become: true
  vars:
    otel_version: "0.105.0"
    otel_config_dir: /etc/otelcol
    otel_config_file: "{{ otel_config_dir }}/config.yaml"
    otel_exporter_otlp_endpoint: "your-remote-endpoint