apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-database-0
  labels:
    app.kubernetes.io/name: my-database
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-fast
  resources:
    requests:
      storage: 50Gi