targetScope = 'subscription'

@description('The object ID of the Azure AD security group to which the custom role will be assigned.')
param securityGroupId string

@description('The name for the custom role. Must be unique within the tenant.')
param roleName string = 'Virtual Machine Read-Only Operator'

@description('A unique name for the role assignment. A new GUID is generated by default.')
param roleAssignmentName string = newGuid()

var roleDefinitionName = guid(subscription().id, roleName)

var readOnlyVMActions = [
  'Microsoft.Compute/virtualMachines/read'
  'Microsoft.Compute/virtualMachines/instanceView/read'
  'Microsoft.Compute/disks/read'
  'Microsoft.Network/networkInterfaces/read'
  'Microsoft.Network/publicIPAddresses/read'
  'Microsoft.Storage/storageAccounts/read'
  'Microsoft.Insights/metrics/read'
  'Microsoft.Insights/logs/read'
  'Microsoft.ResourceHealth/availabilityStatuses/read'
  'Microsoft.Resources/subscriptions/resourceGroups/read'
  'Microsoft.SerialConsole/serialPorts/read'
]

resource customRoleDefinition 'Microsoft.Authorization/roleDefinitions@2022-04-01' = {
  name: roleDefinitionName
  properties: {
    roleName: roleName
    description: 'Grants read-only access to virtual machines and their dependent resources.'
    type: 'CustomRole'
    permissions: [
      {
        actions: readOnlyVMActions
        notActions: []
        dataActions: []
        notDataActions: []
      }
    ]
    assignableScopes: [
      subscription().id
    ]
  }