apiVersion: v1
kind: Service
metadata:
  name: web-frontend-svc
  labels:
    app: web-frontend
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: web-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https