AWSTemplateFormatVersion: '2010-09-09'
Description: 'Provisions a secure S3 bucket for application user uploads with access logging, versioning, and encryption.'

Resources:
  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-access-