---
- name: Deploy Java Application as a systemd service
  hosts: all
  become: true
  vars:
    java_package_name: java-21-openjdk-headless
    app_service_name: my-java-app
    app_service_user: myjavaapp
    app_install_dir: "/opt/{{