apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: my-app-db
type: Opaque
data:
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==