---
- name: Deploy Java Application as a systemd Service
  hosts: all
  become: yes
  vars:
    app_name: "myapp"
    app_user: "myapp_user"
    app_group: "myapp_user"
    app_dir: "/opt/{{ app_name }}"
    app_