AWSTemplateFormatVersion: '2010-09-09'
Description: Provisions an SQS queue and a Lambda function ('order-processor') to process messages from it.

Resources:
  OrderProcessorDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: order-processor-dlq
      MessageRetention