apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-fast
  resources:
    requests:
      storage: 50Gi