apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web-frontend
  template:
    metadata:
      labels:
        app: nginx-web-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-frontend
spec:
  selector:
    app: nginx-web-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer