apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-a-quota
  namespace: team-a
  labels:
    app.kubernetes.io/name: team-a-quota
    app.kubernetes.io/managed-by: kubectl
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "100"